es andlname: Daily AI Analysis Commit

on:
  schedule:
    - cron: "0 6 * * *" # 6 AM UTC daily
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          python -m src.main
