name: Daily News Analysis

on:
  schedule:
    - cron: "0 0 * * *" # Run at midnight UTC daily
  workflow_dispatch: # Allow manual trigger

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Set timeout to prevent hanging jobs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # Enable pip caching

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news analysis
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python src/main.py
        continue-on-error: false # Ensure workflow fails on errors

      - name: Upload error logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: |
            **/*.log
            **/error.txt
          retention-days: 5
