name: Daily AI Analysis Commit

on:
  schedule:
    # Run every 36 minutes (40 times per day)
    - cron: "*/36 * * * *"
  workflow_dispatch:

# Add permissions block
permissions:
  contents: write

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run analysis
        env:
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
        working-directory: ./ # Repository root
        run: |
          python -m src.main
