name: Daily AI Analysis Commit

on:
  schedule:
    - cron: "* * * * *" # Run daily at midnight UTC
  workflow_dispatch:

# Add permissions block
permissions:
  contents: write

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily analysis
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_OWNER: ${{ github.event.repository.owner.login }}
        working-directory: ./ # Repository root
        run: |
          # Create a temporary .env file with the API key
          echo "GOOGLE_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env.temp
          # Run the script with the environment file
          python -c "import os; from dotenv import load_dotenv; load_dotenv('.env.temp'); import src.main"
          # Clean up
          rm .env.temp
