name: Daily AI Analysis Commit

on:
  schedule:
    - cron: "* * * * *" # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: ${{ secrets.REPO_NAME }} # friday1.1
          REPO_OWNER: ${{ secrets.REPO_OWNER }} # harrypeter07
        working-directory: ./ # Repository root
        run: |
          python -m src.main